### ISSUE TITLE
Test Report

### ISSUE THREAD

**Issue by zhangshuoyang** [CS2103AUG2017-T17-B4/main#90] opened 2017-11-03 07:37 UTC
* The mechanism to change theme is not persistent: when you close and reopen the app, the theme will be reverted to the default setting
* The title of the app is not updated
* The GUI does not display the tags properly
	* to reproduce the error, use the following string:	
	* `add n/John Many Long Tag p/98765432 b/02-01-1995 e/johnd@example.com a/311, Clementi Ave 2, #02-25 o/Apple Inc. r/Owe $10 t/friends t/oweeeeeeeeeeeeeee t/1 t/2333333333333 t/3433333333333333` 

* When the last person is restored from Bin, the User Interface shows a white patch
* When the Person List is empty, the UI shows a white patch
* Not sure how to go back from Bin to Person List
* When the Bin is empty, the command `restore 0` and `restore 1` show different error message
* `restore` with numbers greater than Integer.MAX_INT will return "Invalid command format! ", which is misleading
* User Guide 3.19 - "Restore the specified person from the bin to the address book" - is incorrectly stated
* When you execute `export` & `import` command, the example message in the result display does not include Mac's directory

**Comment by FrozVentus** [comment] 2017-11-13 13:06
1) fixed with #110 
2) fixed with #113 
3) maximize window to view the tags properly. Tags are too long, it is recommended to use remark field if you have more things to write about the contact
4) fixed with #110 
5) fixed with #110 
6) use "list". Updated faqs in userguide to address this
7) not a bug, index provided must be a positive integer as stated in user guide
8) not a bug, application is not expected to be able to handle greater than 2,147,483,647 contacts. Delete command have had the same response since addressbook-level4
9) fixed
10) fixed

**Closed as completed by FrozVentus** 2017-11-13 13:06 UTC
